### ISSUE TITLE
Wrong values from the grapher API

### ISSUE THREAD

**Issue by rfc1036** [inex/IXP-Manager#394] opened 2018-03-05 11:31 UTC
##### ISSUE TYPE

 - Bug Report

##### OS

Ubuntu 16.04 for IXP Manager, Debian 9 for MRTG.

##### VERSION

```
define( 'APPLICATION_VERSION', '4.7.3' );
define( 'APPLICATION_VERDATE', '2018021900' );
```

##### ENVIRONMENT 

```
PHP 7.0.27-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jan  5 2018 14:12:46) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.27-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies

ii  php-common                   1:60+ubuntu16.04.1+deb.sury.org+1                        all          Common files for PHP packages
ii  php-ds                       1.2.4-1+ubuntu16.04.1+deb.sury.org+1                     i386         PHP extension providing efficient data structures for PHP 7
ii  php-gettext                  1.0.11-2+deb.sury.org~xenial+1                           all          read gettext MO files directly, without requiring anything other than PHP
ii  php-igbinary                 2.0.5-1+ubuntu16.04.1+deb.sury.org+1                     i386         igbinary PHP serializer
ii  php-memcache                 3.0.9~20160311.4991c2f-7+ubuntu16.04.1+deb.sury.org+1    i386         memcache extension module for PHP
ii  php-memcached                3.0.4+2.2.0-1+ubuntu16.04.1+deb.sury.org+1               i386         memcached extension module for PHP, uses libmemcached
ii  php-msgpack                  2.0.2+0.5.7-1+ubuntu16.04.1+deb.sury.org+3               i386         PHP extension for interfacing with MessagePack
ii  php-pear                     1:1.10.5+submodules+notgz-1+ubuntu16.04.1+deb.sury.org+1 all          PEAR Base System
ii  php-rrd                      2.0.1+1.1.3-4+ubuntu16.04.1+deb.sury.org+1               i386         PHP bindings to rrd tool system
ii  php-yaml                     2.0.2+1.3.1-1+ubuntu16.04.1+deb.sury.org+1               i386         YAML-1.1 parser and emitter for PHP
ii  php7.0                       7.0.27-1+ubuntu16.04.1+deb.sury.org+1                    all          server-side, HTML-embedded scripting language (metapackage)
ii  php7.0-bcmath                7.0.27-1+ubuntu16.04.1+deb.sury.org+1                    i386         Bcmath module for PHP
ii  php7.0-cgi                   7.0.27-1+ubuntu16.04.1+deb.sury.org+1                    i386         server-side, HTML-embedded scripting language (CGI binary)
ii  php7.0-cli                   7.0.27-1+ubuntu16.04.1+deb.sury.org+1                    i386         command-line interpreter for the PHP scripting language
ii  php7.0-common                7.0.27-1+ubuntu16.04.1+deb.sury.org+1                    i386         documentation, examples and common module for PHP
ii  php7.0-curl                  7.0.27-1+ubuntu16.04.1+deb.sury.org+1                    i386         CURL module for PHP
ii  php7.0-fpm                   7.0.27-1+ubuntu16.04.1+deb.sury.org+1                    i386         server-side, HTML-embedded scripting language (FPM-CGI binary)
ii  php7.0-gd                    7.0.27-1+ubuntu16.04.1+deb.sury.org+1                    i386         GD module for PHP
ii  php7.0-intl                  7.0.27-1+ubuntu16.04.1+deb.sury.org+1                    i386         Internationalisation module for PHP
ii  php7.0-json                  7.0.27-1+ubuntu16.04.1+deb.sury.org+1                    i386         JSON module for PHP
ii  php7.0-mbstring              7.0.27-1+ubuntu16.04.1+deb.sury.org+1                    i386         MBSTRING module for PHP
ii  php7.0-mcrypt                7.0.27-1+ubuntu16.04.1+deb.sury.org+1                    i386         libmcrypt module for PHP
ii  php7.0-mysql                 7.0.27-1+ubuntu16.04.1+deb.sury.org+1                    i386         MySQL module for PHP
ii  php7.0-opcache               7.0.27-1+ubuntu16.04.1+deb.sury.org+1                    i386         Zend OpCache module for PHP
ii  php7.0-readline              7.0.27-1+ubuntu16.04.1+deb.sury.org+1                    i386         readline module for PHP
ii  php7.0-snmp                  7.0.27-1+ubuntu16.04.1+deb.sury.org+1                    i386         SNMP module for PHP
ii  php7.0-xml                   7.0.27-1+ubuntu16.04.1+deb.sury.org+1                    i386         DOM, SimpleXML, WDDX, XML, and XSL module for PHP
ii  php7.0-zip                   7.0.27-1+ubuntu16.04.1+deb.sury.org+1                    i386         Zip module for PHP
```

##### CONFIGURATION

```
APP_DEBUG=false
APP_URL="https://manager.minap.it"
APP_TIMEZONE="Europe/Rome"
APP_LOG="single"
IXP_API_JSONEXPORTSCHEMA_PUBLIC=true
IXP_MULTIIXP_ENABLED=false
IXP_RESELLER_ENABLED=false
IXP_AS112_UI_ACTIVE=false
GRAPHER_BACKENDS="mrtg"
GRAPHER_BACKEND_MRTG_DBTYPE="rrd"
GRAPHER_BACKEND_MRTG_SNMPPASSWD=""
GRAPHER_BACKEND_MRTG_WORKDIR="/var/lib/mrtg/"
GRAPHER_BACKEND_MRTG_LOGDIR="/var/lib/mrtg/"
VIEW_SKIN="minap"
VIEW_SMARTY_SKIN="minap"
CACHE_DRIVER=memcached
SESSION_LIFETIME=10080
SESSION_DRIVER=memcached
DOCTRINE_PROXY_AUTOGENERATE=true
DOCTRINE_CACHE=memcached
DOCTRINE_CACHE_NAMESPACE=IXPMANAGERNAMESPACE
IXP_FE_FRONTEND_DISABLED_CONSOLE=true
IXP_FE_FRONTEND_DISABLED_CUSTKIT=true
IXP_FE_FRONTEND_DISABLED_LOOKING_GLASS=false
IXP_FE_LAYER2_ADDRESSES_CUST_CAN_EDIT=true
IXP_FE_LAYER2_ADDRESSES_CUST_PARAMS_MIN_ADDRESSES=1
IXP_FE_LAYER2_ADDRESSES_CUST_PARAMS_MAX_ADDRESSES=2
```

##### SUMMARY

The "json" and "log" formats of the grapher API show different values from the graphs for periods different from "day".

##### STEPS TO REPRODUCE

wget https://manager.minap.it/grapher/ixp?period=month&type=json
wget https://manager.minap.it/grapher/ixp?period=month

##### EXPECTED RESULTS

The numeric values reported by the API should match the values in the graphs.

##### ACTUAL RESULTS

The values are different in periods longer than one days. This is immediately visible for the max/avg values, but it is clear by graphing the values in the log format that they are generally different as well.

**Comment by barryo** [comment] 2021-09-18 10:43
Hi @rfc1036 - I've poked around at this a bit and I cannot reproduce on our own RRDs. E.g. both of these sync up:

* https://www.inex.ie/ixp/grapher/vlan?id=2&protocol=ipv4&type=json
* https://www.inex.ie/ixp/grapher/vlan?id=2&protocol=ipv4

I note the reported version was 4.x but also see on your live system on 6.1 that the issue is still present.

Unfortunately, as I cannot reproduce for rrd files **and** as it appears to be working on the systems I have access to, I need to close this as not-reproducible / can't-fix. 

If you can diagnose yourself and identify the issue, please reopen with details and I'll look again.

**Closed by barryo** 2021-09-18 10:43 UTC
