### ISSUE TITLE
Count wrong for Members by Location

### ISSUE THREAD

**Issue by ninjaix** [inex/IXP-Manager#687] opened 2021-01-09 02:37 UTC
When adding members to a clean new install, members with "n" lag ports are counted as "n" number of members in Members by Location.   I do not believe that that is the intended outcome.    Example if member "Vagrant" has 4 ports in a lag at Barry's Datacenter, Barry's datacenter now shows 4 members.

**Comment by nickhilliard** [comment] 2021-01-09 10:31
duplicate of #688

**Closed by nickhilliard** 2021-01-09 10:31 UTC
