### ISSUE TITLE
FR: Customer interface and SFP port status (rx/tx-power, wavelength, temperature,...) via SNMP

### ISSUE THREAD

**Issue by schadom** [inex/IXP-Manager#658] opened 2020-06-27 12:16 UTC
Show  interface and SFP port status/details from the IXP Switching-infrastructure within the admin and customer backend (if enabled via .env):

- RX-/TX-Errors
- RX-/TX-Power
- Wavelength
- Temperature
etc.

**Comment by barryo** [comment] 2021-09-18 10:44
Duplicate of #465

**Closed by barryo** 2021-09-18 10:44 UTC
