### ISSUE TITLE
Peering matrix [Peer between members]

### ISSUE THREAD

**Issue by cpecus** [inex/IXP-Manager#426] opened 2018-06-25 14:27 UTC
In my peering matrix I can see for example: member1 (peer) with member 2 and the corresponding green box. But in the column of the member2 I should see the same green box with member1, but this is no so.

The version I am using is 4.7.0

**Comment by nickhilliard** [comment] 2018-06-26 22:45
do you have a public URL for this?

**Comment by cpecus** [comment] 2018-06-28 06:42
No, not yet the url is not published. Any way to do a check?

**Comment by nickhilliard** [comment] 2018-06-28 22:50
do you have a quarantine VLAN configured with the same IP address range as your main peering VLAN?

**Comment by cpecus** [comment] 2018-06-29 07:03
No, I only have one vlan configured, I do not have any quarantine vlan. 
I still have the same problem. Can I do some more checking? Thanks

**Comment by barryo** [comment] 2018-11-24 12:09
This code has been completely rewritten. As we cannot reproduce, I an going to close this. If you continue to have this issue in v4.9 (not yet released) then please reopen this. Thanks, Barry

**Closed by barryo** 2018-11-24 12:09 UTC
