### ISSUE TITLE
Client View Statistics

### ISSUE THREAD

**Issue by Yo-Robinson** [inex/IXP-Manager#863] opened 2023-06-30 16:05 UTC
When logged in as a peer connected at an IXP, I have the option to view my per port graphs and aggregated overview.

There is an option to view statistics, but this is a simpler view of the aggregated and per port graphs. It would be great if we could make this a bit more interactive for the user. 

My suggestions:
1. Add the ability to filter graphs per region/location.
2. Include a utilisation indicator i.e flagging ports reaching 60% utilisation.
3. Indication of traffic changes i.e when filtering according to day, week, month and year, the system indicates the overall growth or decline of traffic. This would be applicable to aggregated and per port.

![image](https://github.com/inex/IXP-Manager/assets/62049537/813d19e0-b941-4fde-9f8a-065a4dd52799)

**Comment by barryo** [comment] 2023-07-01 20:55
Thanks @Yo-Robinson for this. 

Advance warning: I'm going to close this issue 😢  - not because you're wrong or that these ideas aren't useful. Only because they're on the list already and this is a duplicate of other issues.

In our annual plans, we have two priorities on the larger task list: (1) overhaul route server configuration + support OpenBGPd; and (2) overhaul the member's portal to include a significant amount or work on graphing and presentation of same to include the suggestions you've made.

Timelines are resource dependent but I'm sketching Q4 for task (1) and 2024Q1 for (2).

**Closed by barryo** 2023-07-01 20:55 UTC

**Comment by Yo-Robinson** [comment] 2023-07-03 17:23
Hi Barry,

Fantastic news! Looking forward to it. :)
