### ISSUE TITLE
Date Left not setable

### ISSUE THREAD

**Issue by netfreak98** [inex/IXP-Manager#456] opened 2018-08-28 16:50 UTC
Currently it is not possible to mark a customer as left. After pressing the "Save Changes" button I get "Customer successfully edited." but the "left" field is still empty.

**Comment by barryo** [comment] 2018-08-28 17:17
I’m pretty sure I did this recently without issue. 

What version are you running?

**Comment by listerr** [comment] 2018-09-11 13:04
Possibly duplicate of #438 ?
I had same issue but was fixed.

**Comment by barryo** [comment] 2018-09-11 13:08
Thanks @listerr - looks like a dub alright. Fixed in master.

**Closed by barryo** 2018-09-11 13:08 UTC
Labels: Bug

**Comment by netfreak98** [comment] 2018-12-20 09:30
Hi, the Problem still persists for us using manager version V4.8.0

**Comment by netfreak98** [comment] 2018-12-20 09:31
Can you please reopen this issue?

**Comment by nickhilliard** [comment] 2018-12-20 10:19
@netfreak98 the problem exists in 4.8.0 but was fixed in commit d1453d5b17418b1eed567238ce9ad8f1c9cd7a36.  We're planning to release 4.9.0 shortly, which will have the fix included.

**Comment by netfreak98** [comment] 2019-01-09 13:18
I can confirm, it is fixed now. Thanks! :)
