### ISSUE TITLE
Help in installation

### ISSUE THREAD

**Issue by AFKD98** [inex/IXP-Manager#540] opened 2019-07-07 21:02 UTC
Dear Sir/Madam,
                          I am new to IXP. I am doing research on IXP manager and IXP in Lahore University of Management Sciences. I need some with below-mentioned errors.

I am using this mechanism here:
https://github.com/inex/IXP-Manager/tree/master/tools/installers 
But I am doing on VMware installed on windows.

On vagrant up --provision, The error is:
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

For that, I followed and added two lines in sudoers file of the guest but that couldn't help. 
https://github.com/hashicorp/vagrant/issues/1659#issuecomment-17046154

/tmp/ixp-manager-install.log  gives this error after installing. 
error: object file .git/objects/af/1b6fcce0eea3de14854fe50a787e3b0851ba38 is em$
fatal: loose object af1b6fcce0eea3de14854fe50a787e3b0851ba38 (stored in .git/ob$
fatal: unpack-objects failed

Kindly help me. I have been installing from 3 weeks.

**Comment by barryo** [comment] 2019-07-08 06:12
Closing -> this is a duplicate of a mailing list thread.

**Closed by barryo** 2019-07-08 06:12 UTC
