### ISSUE TITLE
Broken links in the Switches wiew

### ISSUE THREAD

**Issue by rfc1036** [inex/IXP-Manager#377] opened 2018-01-23 15:36 UTC
The "Cabinet" links in .../switch/list link to URLs like .../cabinet/view/id/1, which do not exist.

**Comment by barryo** [comment] 2018-01-23 15:42
Thanks @rfc1036 but this is actually a duplicate of #363 and is already fixed in master.

**Closed by barryo** 2018-01-23 15:42 UTC
