### ISSUE TITLE
Message: Syntax error in template "/usr/local/ixp/application/views/admin/index.phtml"  on line 217 "{genMrtgGraphBox" unknown tag "genMrtgGraphBox"

### ISSUE THREAD

**Issue by uixp** [inex/IXP-Manager#225] opened 2015-07-12 11:25 UTC
I am getting the above error after fetching changes from master branch. Checked if Smarty library submodule also up to date.

**Comment by barryo** [comment] 2015-07-12 15:02
Hi,

this looks like a Smarty path issue. Same code is working fine for a number of IXPs in production.

Check the relevant sections in `application/configs/application.ini` and ensure you have:

```ini
resources.smarty.plugins[] = APPLICATION_PATH "/../library/inex-smarty/functions"
resources.smarty.plugins[] = APPLICATION_PATH "/../library/OSS-Framework.git/OSS/Smarty/functions"
resources.smarty.plugins[] = APPLICATION_PATH "/../library/Smarty/plugins"
resources.smarty.plugins[] = APPLICATION_PATH "/../library/Smarty/sysplugins"
```

without typos / changes and in that order. 

Closing as this is not a bug. Feel free to follow up here or move over to the mailing list.

**Closed by barryo** 2015-07-12 15:02 UTC

**Comment by uixp** [comment] 2015-07-12 17:55
Thanks for the pointer found the broken plugin path!
