### ISSUE TITLE
Mailinglist Init function broken - Zend exception d2em entry missing

### ISSUE THREAD

**Issue by saschaboerner** [inex/IXP-Manager#368] opened 2018-01-02 11:35 UTC
Version: 4.7.0
Command: artisan mailing-list:init members < </tmp/ml-members.txt
Output:
Setting mailing list subscription for all users without a pre-existing subscription setting...
[Zend_Exception]
No entry is registered for key 'd2em'

When using API v4 it produces an Error 500, maybe the same problem.

The mailing list feature has just been implemented at our site, so there is only one user with a matching preference at the database, I removed these flags for testing, no change. The error comes out of app/Utils/MailingList.php line 121:
if( $u->hasPreference( "mailinglist.{$this->key}.subscribed" ) ) {

**Comment by barryo** [comment] 2018-01-02 11:43
Cannot reproduce on our own production install.

Will try to reproduce on a development version.

**Comment by yannrobin** [comment] 2018-01-18 15:31
@barryo that the same issue that I had when I did the customer management on Laravel.
The Laravel controller try use \Zend_Registry::get( 'd2em' )[ 'default' ];

This issue will be fixed on the new Update of IXP-Manager

**Comment by saschaboerner** [comment] 2018-01-18 15:32
Thank you!

**Comment by saschaboerner** [comment] 2018-02-02 08:25
New error message with 4.7.2:
Command: /usr/lib/mailman/bin/list_members members | $IXPROOT/artisan mailing-list:init members
Setting mailing list subscription for all users without a pre-existing subscription setting...
In Registry.php line 147:
No entry is registered for key 'd2em'

**Comment by barryo** [comment] 2018-02-02 08:53
Yip, same issue. Fix in 4.8.0 later this month I imagine.

**Comment by digitalandrei** [comment] 2018-03-08 13:47
Hello Barry :)

Any updates on this? We would like to implement the feature and we are stuck at the error mentioned by Sascha.

Thank you

**Closed** 2018-03-19 10:35 UTC

**Comment by MHammett** [comment] 2018-03-19 13:58
Which version is working for you?

**Comment by digitalandrei** [comment] 2018-03-19 14:27
The dev version 4.7.999.

**Comment by MHammett** [comment] 2018-03-19 14:34
Oh, okay. I'll keep watching the changelogs.
